### ISSUE TITLE
Falta elaborar os fluxos dos casos de uso.

### ISSUE THREAD

**Issue by tmsasaki** [tadashl/ppads-projeto-05K#9]

**Comment by sephirotty** [comment]
[fluxos.pdf](https://github.com/tadashl/ppads-projeto-05K/files/1862312/fluxos.pdf)

**Comment by jmtechn** [comment]
[fluxos.pdf](https://github.com/tadashl/ppads-projeto-05K/files/1956210/fluxos.pdf)

Atualizado!
